/**
 * Business-day calendars for payroll-tax due dates.
 *
 * Federal (IRS): "legal holiday" means any legal holiday in the District of Columbia, and a due date
 * on a Saturday, Sunday or legal holiday moves to the next business day (Pub 15, "Legal holidays";
 * "If any date ... falls on a Saturday, Sunday, or legal holiday, the due date is the next business day").
 * The holidays are generated by rule (5 U.S.C. 6103 plus DC Emancipation Day and Inauguration Day)
 * and the test suite checks the generator against Pub 15 (2026)'s printed list.
 *
 * California (EDD): due dates on a "Saturday, Sunday, or legal holiday" move to the next business day
 * (DE 44 2026, pp. 13 and 68). California's legal holidays (Gov. Code 6700) include moving dates
 * (Lunar New Year, Diwali, a partial Good Friday) and it isn't documented which ones the EDD honours.
 * So this calendar deliberately ERRS EARLY: it only counts days that are BOTH a federal holiday and
 * in Gov. Code 6700, on their actual dates (no weekend "observed" shifts). A holiday it misses can
 * only make a computed due date earlier than the real one, never later.
 */

export type Jurisdiction = "US" | "US-CA";

const pad = (n: number) => String(n).padStart(2, "0");
export const iso = (y: number, m: number, d: number) => `${y}-${pad(m)}-${pad(d)}`;
const utc = (s: string) => new Date(`${s}T12:00:00Z`);
const fmt = (d: Date) => d.toISOString().slice(0, 10);
export const addDays = (s: string, n: number) => fmt(new Date(utc(s).getTime() + n * 864e5));
export const weekday = (s: string) => utc(s).getUTCDay();          // 0 Sun .. 6 Sat
const isWeekend = (s: string) => [0, 6].includes(weekday(s));

/** nth (1-based) weekday `wd` of a month; n = -1 for the last one. */
function nthWeekday(y: number, m: number, wd: number, n: number): string {
  if (n > 0) {
    const first = weekday(iso(y, m, 1));
    return iso(y, m, 1 + ((wd - first + 7) % 7) + (n - 1) * 7);
  }
  const lastDay = new Date(Date.UTC(y, m, 0)).getUTCDate();
  const last = weekday(iso(y, m, lastDay));
  return iso(y, m, lastDay - ((last - wd + 7) % 7));
}

/** Saturday -> preceding Friday, Sunday -> following Monday (5 U.S.C. 6103(b)). */
const observed = (s: string) => weekday(s) === 6 ? addDays(s, -1) : weekday(s) === 0 ? addDays(s, 1) : s;

export interface Holiday { date: string; name: string }

/** DC legal holidays observed in calendar year `y` (what Pub 15 lists for the deposit rules). */
export function federalHolidays(y: number): Holiday[] {
  const fixed = (m: number, d: number, name: string, yy = y): Holiday => ({ date: observed(iso(yy, m, d)), name });
  const list: Holiday[] = [
    fixed(1, 1, "New Year's Day"),
    fixed(1, 1, "New Year's Day", y + 1),                      // Jan 1 on a Saturday is observed Dec 31
    { date: nthWeekday(y, 1, 1, 3), name: "Birthday of Martin Luther King, Jr." },
    { date: nthWeekday(y, 2, 1, 3), name: "Washington's Birthday" },
    fixed(4, 16, "District of Columbia Emancipation Day"),
    { date: nthWeekday(y, 5, 1, -1), name: "Memorial Day" },
    fixed(6, 19, "Juneteenth National Independence Day"),
    fixed(7, 4, "Independence Day"),
    { date: nthWeekday(y, 9, 1, 1), name: "Labor Day" },
    { date: nthWeekday(y, 10, 1, 2), name: "Indigenous Peoples' Day (Columbus Day)" },
    fixed(11, 11, "Veterans Day"),
    { date: nthWeekday(y, 11, 4, 4), name: "Thanksgiving Day" },
    fixed(12, 25, "Christmas Day"),
  ];
  // Inauguration Day is a DC legal holiday every fourth year (2025, 2029, ...); Sunday moves to Monday.
  if ((y - 2025) % 4 === 0) {
    const d = iso(y, 1, 20);
    list.push({ date: weekday(d) === 0 ? addDays(d, 1) : d, name: "Inauguration Day" });
  }
  return list.filter(h => h.date.startsWith(`${y}-`)).sort((a, b) => a.date.localeCompare(b.date));
}

/** Conservative California set: federal holidays that are also in Gov. Code 6700, on their actual dates. */
export function californiaHolidays(y: number): Holiday[] {
  return [
    { date: iso(y, 1, 1), name: "New Year's Day" },
    { date: nthWeekday(y, 1, 1, 3), name: "Martin Luther King, Jr. Day" },
    { date: nthWeekday(y, 2, 1, 3), name: "Presidents' Day (third Monday in February)" },
    { date: nthWeekday(y, 5, 1, -1), name: "Memorial Day" },
    { date: iso(y, 6, 19), name: "Juneteenth" },
    { date: iso(y, 7, 4), name: "Independence Day" },
    { date: nthWeekday(y, 9, 1, 1), name: "Labor Day" },
    { date: nthWeekday(y, 10, 1, 2), name: "Columbus Day" },
    { date: iso(y, 11, 11), name: "Veterans Day" },
    { date: nthWeekday(y, 11, 4, 4), name: "Thanksgiving Day" },
    { date: iso(y, 12, 25), name: "Christmas Day" },
  ].filter(h => !isWeekend(h.date));
}

const cache = new Map<string, Set<string>>();
function holidaySet(j: Jurisdiction, y: number): Set<string> {
  const k = `${j}:${y}`;
  let s = cache.get(k);
  if (!s) { s = new Set((j === "US" ? federalHolidays(y) : californiaHolidays(y)).map(h => h.date)); cache.set(k, s); }
  return s;
}

export const isBusinessDay = (s: string, j: Jurisdiction) => !isWeekend(s) && !holidaySet(j, Number(s.slice(0, 4))).has(s);

/** The date itself if it's a business day, otherwise the next business day. */
export function onOrNextBusinessDay(s: string, j: Jurisdiction): string {
  let d = s;
  while (!isBusinessDay(d, j)) d = addDays(d, 1);
  return d;
}

/** `n` business days before `s` (n >= 1). */
export function businessDaysBefore(s: string, n: number, j: Jurisdiction): string {
  let d = s, left = n;
  while (left > 0) { d = addDays(d, -1); if (isBusinessDay(d, j)) left--; }
  return d;
}

export const lastDayOfMonth = (y: number, m: number) => iso(y, m, new Date(Date.UTC(y, m, 0)).getUTCDate());
